#pragma once

// Typed wrappers for every unary RPC of the T-Invest API.
//
// Each RPC yields three overloads generated by TINVEST_RPC:
//   Result<Resp> name(const Req& = {}, const CallOptions& = {});   // blocking
//   void         name(Req, Callback<Resp>, const CallOptions& = {}); // async
//   awaiter      name(Req, use_awaitable_t, const CallOptions& = {}); // co_await
//
// The async/awaitable overloads complete on a gRPC worker thread and are
// never retried by the SDK; the blocking overload honours Config::retry.
// All overloads consult the client-side RateLimiter when it is configured.

#include <memory>
#include <string>
#include <utility>

#include "tinvest/awaitable.hpp"
#include "tinvest/client.hpp"
#include "tinvest/detail/unary.hpp"
#include "tinvest/pb_grpc.hpp"

#define TINVEST_RPC(name, Rpc, ReqT, RespT)                                    \
  Result<RespT> name(const ReqT& req = {}, const CallOptions& opts = {}) {     \
    static const std::string kMethod =                                         \
        std::string(kServiceFullName) + "/" + #Rpc;                            \
    return ::tinvest::detail::unary_sync<RespT>(                               \
        *client_, opts, kMethod,                                               \
        [&](grpc::ClientContext& ctx, RespT* resp) {                           \
          return stub_->Rpc(&ctx, req, resp);                                  \
        });                                                                    \
  }                                                                            \
  void name(ReqT req, Callback<RespT> cb, const CallOptions& opts = {}) {      \
    static const std::string kMethod =                                         \
        std::string(kServiceFullName) + "/" + #Rpc;                            \
    ::tinvest::detail::unary_async<ReqT, RespT>(                               \
        *client_, opts, kMethod, std::move(req), std::move(cb),                \
        [this](grpc::ClientContext* ctx, const ReqT* r, RespT* resp,           \
               std::function<void(grpc::Status)> done) {                       \
          stub_->async()->Rpc(ctx, r, resp, std::move(done));                  \
        });                                                                    \
  }                                                                            \
  auto name(ReqT req, use_awaitable_t, const CallOptions& opts = {}) {         \
    return ::tinvest::detail::UnaryAwaiter<RespT>(                             \
        [this, req = std::move(req), opts](Callback<RespT> cb) mutable {       \
          this->name(std::move(req), std::move(cb), opts);                     \
        });                                                                    \
  }

namespace tinvest {

class UsersService {
 public:
  static constexpr const char* kServiceFullName =
      "tinkoff.public.invest.api.contract.v1.UsersService";
  explicit UsersService(Client& client)
      : client_(&client), stub_(pb::UsersService::NewStub(client.channel())) {}

  TINVEST_RPC(get_accounts, GetAccounts, pb::GetAccountsRequest,
              pb::GetAccountsResponse)
  TINVEST_RPC(get_margin_attributes, GetMarginAttributes,
              pb::GetMarginAttributesRequest, pb::GetMarginAttributesResponse)
  TINVEST_RPC(get_user_tariff, GetUserTariff, pb::GetUserTariffRequest,
              pb::GetUserTariffResponse)
  TINVEST_RPC(get_info, GetInfo, pb::GetInfoRequest, pb::GetInfoResponse)
  TINVEST_RPC(get_bank_accounts, GetBankAccounts, pb::GetBankAccountsRequest,
              pb::GetBankAccountsResponse)
  TINVEST_RPC(currency_transfer, CurrencyTransfer, pb::CurrencyTransferRequest,
              pb::CurrencyTransferResponse)

 private:
  Client* client_;
  std::unique_ptr<pb::UsersService::Stub> stub_;
};

class InstrumentsService {
 public:
  static constexpr const char* kServiceFullName =
      "tinkoff.public.invest.api.contract.v1.InstrumentsService";
  explicit InstrumentsService(Client& client)
      : client_(&client),
        stub_(pb::InstrumentsService::NewStub(client.channel())) {}

  TINVEST_RPC(trading_schedules, TradingSchedules, pb::TradingSchedulesRequest,
              pb::TradingSchedulesResponse)
  TINVEST_RPC(bond_by, BondBy, pb::InstrumentRequest, pb::BondResponse)
  TINVEST_RPC(bonds, Bonds, pb::InstrumentsRequest, pb::BondsResponse)
  TINVEST_RPC(get_bond_coupons, GetBondCoupons, pb::GetBondCouponsRequest,
              pb::GetBondCouponsResponse)
  TINVEST_RPC(get_bond_events, GetBondEvents, pb::GetBondEventsRequest,
              pb::GetBondEventsResponse)
  TINVEST_RPC(currency_by, CurrencyBy, pb::InstrumentRequest,
              pb::CurrencyResponse)
  TINVEST_RPC(currencies, Currencies, pb::InstrumentsRequest,
              pb::CurrenciesResponse)
  TINVEST_RPC(etf_by, EtfBy, pb::InstrumentRequest, pb::EtfResponse)
  TINVEST_RPC(etfs, Etfs, pb::InstrumentsRequest, pb::EtfsResponse)
  TINVEST_RPC(future_by, FutureBy, pb::InstrumentRequest, pb::FutureResponse)
  TINVEST_RPC(futures, Futures, pb::InstrumentsRequest, pb::FuturesResponse)
  TINVEST_RPC(option_by, OptionBy, pb::InstrumentRequest, pb::OptionResponse)
  TINVEST_RPC(options, Options, pb::InstrumentsRequest, pb::OptionsResponse)
  TINVEST_RPC(options_by, OptionsBy, pb::FilterOptionsRequest,
              pb::OptionsResponse)
  TINVEST_RPC(share_by, ShareBy, pb::InstrumentRequest, pb::ShareResponse)
  TINVEST_RPC(shares, Shares, pb::InstrumentsRequest, pb::SharesResponse)
  TINVEST_RPC(indicatives, Indicatives, pb::IndicativesRequest,
              pb::IndicativesResponse)
  TINVEST_RPC(get_accrued_interests, GetAccruedInterests,
              pb::GetAccruedInterestsRequest, pb::GetAccruedInterestsResponse)
  TINVEST_RPC(get_futures_margin, GetFuturesMargin, pb::GetFuturesMarginRequest,
              pb::GetFuturesMarginResponse)
  TINVEST_RPC(get_instrument_by, GetInstrumentBy, pb::InstrumentRequest,
              pb::InstrumentResponse)
  TINVEST_RPC(get_dividends, GetDividends, pb::GetDividendsRequest,
              pb::GetDividendsResponse)
  TINVEST_RPC(get_asset_by, GetAssetBy, pb::AssetRequest, pb::AssetResponse)
  TINVEST_RPC(get_assets, GetAssets, pb::AssetsRequest, pb::AssetsResponse)
  TINVEST_RPC(get_favorites, GetFavorites, pb::GetFavoritesRequest,
              pb::GetFavoritesResponse)
  TINVEST_RPC(edit_favorites, EditFavorites, pb::EditFavoritesRequest,
              pb::EditFavoritesResponse)
  TINVEST_RPC(create_favorite_group, CreateFavoriteGroup,
              pb::CreateFavoriteGroupRequest, pb::CreateFavoriteGroupResponse)
  TINVEST_RPC(delete_favorite_group, DeleteFavoriteGroup,
              pb::DeleteFavoriteGroupRequest, pb::DeleteFavoriteGroupResponse)
  TINVEST_RPC(get_favorite_groups, GetFavoriteGroups,
              pb::GetFavoriteGroupsRequest, pb::GetFavoriteGroupsResponse)
  TINVEST_RPC(get_countries, GetCountries, pb::GetCountriesRequest,
              pb::GetCountriesResponse)
  TINVEST_RPC(find_instrument, FindInstrument, pb::FindInstrumentRequest,
              pb::FindInstrumentResponse)
  TINVEST_RPC(get_brands, GetBrands, pb::GetBrandsRequest,
              pb::GetBrandsResponse)
  TINVEST_RPC(get_brand_by, GetBrandBy, pb::GetBrandRequest, pb::Brand)
  TINVEST_RPC(get_asset_fundamentals, GetAssetFundamentals,
              pb::GetAssetFundamentalsRequest,
              pb::GetAssetFundamentalsResponse)
  TINVEST_RPC(get_asset_reports, GetAssetReports, pb::GetAssetReportsRequest,
              pb::GetAssetReportsResponse)
  TINVEST_RPC(get_consensus_forecasts, GetConsensusForecasts,
              pb::GetConsensusForecastsRequest,
              pb::GetConsensusForecastsResponse)
  TINVEST_RPC(get_forecast_by, GetForecastBy, pb::GetForecastRequest,
              pb::GetForecastResponse)
  TINVEST_RPC(get_risk_rates, GetRiskRates, pb::RiskRatesRequest,
              pb::RiskRatesResponse)
  TINVEST_RPC(get_insider_deals, GetInsiderDeals, pb::GetInsiderDealsRequest,
              pb::GetInsiderDealsResponse)
  TINVEST_RPC(structured_note_by, StructuredNoteBy, pb::InstrumentRequest,
              pb::StructuredNoteResponse)
  TINVEST_RPC(structured_notes, StructuredNotes, pb::InstrumentsRequest,
              pb::StructuredNotesResponse)

 private:
  Client* client_;
  std::unique_ptr<pb::InstrumentsService::Stub> stub_;
};

class MarketDataService {
 public:
  static constexpr const char* kServiceFullName =
      "tinkoff.public.invest.api.contract.v1.MarketDataService";
  explicit MarketDataService(Client& client)
      : client_(&client),
        stub_(pb::MarketDataService::NewStub(client.channel())) {}

  TINVEST_RPC(get_candles, GetCandles, pb::GetCandlesRequest,
              pb::GetCandlesResponse)
  TINVEST_RPC(get_last_prices, GetLastPrices, pb::GetLastPricesRequest,
              pb::GetLastPricesResponse)
  TINVEST_RPC(get_order_book, GetOrderBook, pb::GetOrderBookRequest,
              pb::GetOrderBookResponse)
  TINVEST_RPC(get_trading_status, GetTradingStatus, pb::GetTradingStatusRequest,
              pb::GetTradingStatusResponse)
  TINVEST_RPC(get_trading_statuses, GetTradingStatuses,
              pb::GetTradingStatusesRequest, pb::GetTradingStatusesResponse)
  TINVEST_RPC(get_last_trades, GetLastTrades, pb::GetLastTradesRequest,
              pb::GetLastTradesResponse)
  TINVEST_RPC(get_close_prices, GetClosePrices, pb::GetClosePricesRequest,
              pb::GetClosePricesResponse)
  TINVEST_RPC(get_tech_analysis, GetTechAnalysis, pb::GetTechAnalysisRequest,
              pb::GetTechAnalysisResponse)
  TINVEST_RPC(get_market_values, GetMarketValues, pb::GetMarketValuesRequest,
              pb::GetMarketValuesResponse)

 private:
  Client* client_;
  std::unique_ptr<pb::MarketDataService::Stub> stub_;
};

class OperationsService {
 public:
  static constexpr const char* kServiceFullName =
      "tinkoff.public.invest.api.contract.v1.OperationsService";
  explicit OperationsService(Client& client)
      : client_(&client),
        stub_(pb::OperationsService::NewStub(client.channel())) {}

  TINVEST_RPC(get_operations, GetOperations, pb::OperationsRequest,
              pb::OperationsResponse)
  TINVEST_RPC(get_portfolio, GetPortfolio, pb::PortfolioRequest,
              pb::PortfolioResponse)
  TINVEST_RPC(get_positions, GetPositions, pb::PositionsRequest,
              pb::PositionsResponse)
  TINVEST_RPC(get_withdraw_limits, GetWithdrawLimits, pb::WithdrawLimitsRequest,
              pb::WithdrawLimitsResponse)
  TINVEST_RPC(get_broker_report, GetBrokerReport, pb::BrokerReportRequest,
              pb::BrokerReportResponse)
  TINVEST_RPC(get_dividends_foreign_issuer, GetDividendsForeignIssuer,
              pb::GetDividendsForeignIssuerRequest,
              pb::GetDividendsForeignIssuerResponse)
  TINVEST_RPC(get_operations_by_cursor, GetOperationsByCursor,
              pb::GetOperationsByCursorRequest,
              pb::GetOperationsByCursorResponse)

 private:
  Client* client_;
  std::unique_ptr<pb::OperationsService::Stub> stub_;
};

class OrdersService {
 public:
  static constexpr const char* kServiceFullName =
      "tinkoff.public.invest.api.contract.v1.OrdersService";
  explicit OrdersService(Client& client)
      : client_(&client), stub_(pb::OrdersService::NewStub(client.channel())) {}

  TINVEST_RPC(post_order, PostOrder, pb::PostOrderRequest,
              pb::PostOrderResponse)
  TINVEST_RPC(post_order_async, PostOrderAsync, pb::PostOrderAsyncRequest,
              pb::PostOrderAsyncResponse)
  TINVEST_RPC(cancel_order, CancelOrder, pb::CancelOrderRequest,
              pb::CancelOrderResponse)
  TINVEST_RPC(get_order_state, GetOrderState, pb::GetOrderStateRequest,
              pb::OrderState)
  TINVEST_RPC(get_orders, GetOrders, pb::GetOrdersRequest,
              pb::GetOrdersResponse)
  TINVEST_RPC(replace_order, ReplaceOrder, pb::ReplaceOrderRequest,
              pb::PostOrderResponse)
  TINVEST_RPC(get_max_lots, GetMaxLots, pb::GetMaxLotsRequest,
              pb::GetMaxLotsResponse)
  TINVEST_RPC(get_order_price, GetOrderPrice, pb::GetOrderPriceRequest,
              pb::GetOrderPriceResponse)

 private:
  Client* client_;
  std::unique_ptr<pb::OrdersService::Stub> stub_;
};

class StopOrdersService {
 public:
  static constexpr const char* kServiceFullName =
      "tinkoff.public.invest.api.contract.v1.StopOrdersService";
  explicit StopOrdersService(Client& client)
      : client_(&client),
        stub_(pb::StopOrdersService::NewStub(client.channel())) {}

  TINVEST_RPC(post_stop_order, PostStopOrder, pb::PostStopOrderRequest,
              pb::PostStopOrderResponse)
  TINVEST_RPC(get_stop_orders, GetStopOrders, pb::GetStopOrdersRequest,
              pb::GetStopOrdersResponse)
  TINVEST_RPC(cancel_stop_order, CancelStopOrder, pb::CancelStopOrderRequest,
              pb::CancelStopOrderResponse)

 private:
  Client* client_;
  std::unique_ptr<pb::StopOrdersService::Stub> stub_;
};

class SandboxService {
 public:
  static constexpr const char* kServiceFullName =
      "tinkoff.public.invest.api.contract.v1.SandboxService";
  explicit SandboxService(Client& client)
      : client_(&client),
        stub_(pb::SandboxService::NewStub(client.channel())) {}

  TINVEST_RPC(open_sandbox_account, OpenSandboxAccount,
              pb::OpenSandboxAccountRequest, pb::OpenSandboxAccountResponse)
  TINVEST_RPC(get_sandbox_accounts, GetSandboxAccounts, pb::GetAccountsRequest,
              pb::GetAccountsResponse)
  TINVEST_RPC(close_sandbox_account, CloseSandboxAccount,
              pb::CloseSandboxAccountRequest, pb::CloseSandboxAccountResponse)
  TINVEST_RPC(post_sandbox_order, PostSandboxOrder, pb::PostOrderRequest,
              pb::PostOrderResponse)
  TINVEST_RPC(post_sandbox_order_async, PostSandboxOrderAsync,
              pb::PostOrderAsyncRequest, pb::PostOrderAsyncResponse)
  TINVEST_RPC(replace_sandbox_order, ReplaceSandboxOrder,
              pb::ReplaceOrderRequest, pb::PostOrderResponse)
  TINVEST_RPC(get_sandbox_orders, GetSandboxOrders, pb::GetOrdersRequest,
              pb::GetOrdersResponse)
  TINVEST_RPC(cancel_sandbox_order, CancelSandboxOrder, pb::CancelOrderRequest,
              pb::CancelOrderResponse)
  TINVEST_RPC(get_sandbox_order_state, GetSandboxOrderState,
              pb::GetOrderStateRequest, pb::OrderState)
  TINVEST_RPC(get_sandbox_order_price, GetSandboxOrderPrice,
              pb::GetOrderPriceRequest, pb::GetOrderPriceResponse)
  TINVEST_RPC(get_sandbox_positions, GetSandboxPositions, pb::PositionsRequest,
              pb::PositionsResponse)
  TINVEST_RPC(get_sandbox_operations, GetSandboxOperations,
              pb::OperationsRequest, pb::OperationsResponse)
  TINVEST_RPC(get_sandbox_operations_by_cursor, GetSandboxOperationsByCursor,
              pb::GetOperationsByCursorRequest,
              pb::GetOperationsByCursorResponse)
  TINVEST_RPC(get_sandbox_portfolio, GetSandboxPortfolio, pb::PortfolioRequest,
              pb::PortfolioResponse)
  TINVEST_RPC(sandbox_pay_in, SandboxPayIn, pb::SandboxPayInRequest,
              pb::SandboxPayInResponse)
  TINVEST_RPC(get_sandbox_withdraw_limits, GetSandboxWithdrawLimits,
              pb::WithdrawLimitsRequest, pb::WithdrawLimitsResponse)
  TINVEST_RPC(get_sandbox_max_lots, GetSandboxMaxLots, pb::GetMaxLotsRequest,
              pb::GetMaxLotsResponse)
  TINVEST_RPC(post_sandbox_stop_order, PostSandboxStopOrder,
              pb::PostStopOrderRequest, pb::PostStopOrderResponse)
  TINVEST_RPC(get_sandbox_stop_orders, GetSandboxStopOrders,
              pb::GetStopOrdersRequest, pb::GetStopOrdersResponse)
  TINVEST_RPC(cancel_sandbox_stop_order, CancelSandboxStopOrder,
              pb::CancelStopOrderRequest, pb::CancelStopOrderResponse)

 private:
  Client* client_;
  std::unique_ptr<pb::SandboxService::Stub> stub_;
};

class SignalService {
 public:
  static constexpr const char* kServiceFullName =
      "tinkoff.public.invest.api.contract.v1.SignalService";
  explicit SignalService(Client& client)
      : client_(&client), stub_(pb::SignalService::NewStub(client.channel())) {}

  TINVEST_RPC(get_strategies, GetStrategies, pb::GetStrategiesRequest,
              pb::GetStrategiesResponse)
  TINVEST_RPC(get_signals, GetSignals, pb::GetSignalsRequest,
              pb::GetSignalsResponse)

 private:
  Client* client_;
  std::unique_ptr<pb::SignalService::Stub> stub_;
};

}  // namespace tinvest

#undef TINVEST_RPC
